package org.example.ticketingapplication.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Ticket Entity - Represents a support ticket in the system.
 *
 * Database Mapping:
 * - Table: ticket
 * - Persistence Strategy: JPA/Hibernate ORM
 * - Caching: Instances are cached in Redis with key "ticket:{id}" and TTL 30 minutes
 *
 * Indexes (for optimal query performance):
 * - idx_ticket_number: Unique index on ticket_number (fast lookups)
 * - idx_status: Index on status (filtering by status)
 * - idx_customer_id: Index on customer_id (customer-specific queries)
 * - idx_assigned_to: Index on assigned_to (user assignment queries)
 * - idx_created_at: Index on created_at (time-range queries)
 *
 * Serialization:
 * - Implements Serializable for Redis caching
 * - serialVersionUID: For version compatibility
 * - JSON serialization: Handled by Jackson via TicketResponse DTO
 *
 * Design Pattern:
 * - Persistence-only entity (no business logic)
 * - All business logic in service layer (TicketService/TicketServiceImpl)
 * - DTO mapping: Ticket entity → TicketResponse DTO before JSON serialization
 *
 * Cache Invalidation:
 * - On create: No cache (new ticket)
 * - On update: Cache key "ticket:{id}" is deleted
 * - On delete: Cache key "ticket:{id}" is deleted
 * - On bulk operations: Pattern "ticket:*" is deleted
 *
 * @author Enterprise Backend Team
 * @version 1.0
 */
@Entity
@Table(
    name = "ticket",
    indexes = {
        @Index(name = "idx_ticket_number", columnList = "ticket_number", unique = true),
        @Index(name = "idx_status", columnList = "status"),
        @Index(name = "idx_customer_id", columnList = "customer_id"),
        @Index(name = "idx_assigned_to", columnList = "assigned_to"),
        @Index(name = "idx_created_at", columnList = "created_at")
    }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {}) // Include all fields in toString
@EqualsAndHashCode(exclude = {"createdAt"}) // Exclude timestamp from equality
public class Ticket implements Serializable {

    /**
     * Serial version UID for serialization compatibility.
     * Update this when entity structure changes significantly.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Primary Key - Unique identifier for the ticket.
     * Auto-generated by database using IDENTITY strategy.
     * Range: 1 to Long.MAX_VALUE
     * Used as Redis cache key suffix: "ticket:{id}"
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Unique ticket number - Human-readable identifier.
     * Example format: "TICKET-2025-001", "TKT-20251226-001"
     * Constraints: Unique, Required, max 50 characters
     * Index: idx_ticket_number (unique constraint for fast lookups)
     * Used by clients to reference tickets in support interactions
     */
    @Column(name = "ticket_number", unique = true, nullable = false, length = 50)
    private String ticketNumber;

    /**
     * Current status of the ticket.
     * Valid values: OPEN, IN_PROGRESS, RESOLVED, CLOSED, ON_HOLD
     * Constraints: Required, max 50 characters
     * Index: idx_status (for filtering tickets by status)
     * Updatable via PUT /api/v1/tickets/{id}
     * Change triggers cache invalidation
     */
    @Column(name = "status", nullable = false, length = 50)
    private String status;

    /**
     * Priority level of the ticket.
     * Valid values: LOW, MEDIUM, HIGH, CRITICAL
     * Constraints: Required, max 50 characters
     * Determines handling urgency and SLA response times
     * Updatable via PUT /api/v1/tickets/{id}
     * Change triggers cache invalidation
     */
    @Column(name = "priority", nullable = false, length = 50)
    private String priority;

    /**
     * Timestamp when the ticket was created.
     * Automatically set by Hibernate via @CreationTimestamp
     * Constraints: Required, not updatable
     * Format: LocalDateTime (YYYY-MM-DD HH:MM:SS)
     * Index: idx_created_at (for time-range queries and sorting)
     * Used for ticket age calculations and SLA tracking
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Customer ID who reported/created the ticket.
     * References external customer system (non-JPA relationship)
     * Constraints: Optional
     * Index: idx_customer_id (for customer-specific queries)
     * Used to retrieve all tickets from a specific customer
     */
    @Column(name = "customer_id")
    private Long customerId;

    /**
     * User ID of the person assigned to this ticket.
     * References internal user system (non-JPA relationship)
     * Constraints: Optional (can be null if unassigned)
     * Index: idx_assigned_to (for user assignment queries)
     * Can be updated via PUT /api/v1/tickets/{id}
     * Supports ticket assignment and workload distribution
     */
    @Column(name = "assigned_to")
    private Integer assignedTo;
}
