package org.example.ticketingapplication.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;

/**
 * Data Transfer Object for creating a new ticket.
 *
 * This DTO is used in POST /api/v1/tickets endpoint to accept ticket creation requests.
 * All fields are validated using Jakarta Bean Validation (formerly javax.validation).
 *
 * Validation Rules:
 * - ticketNumber: Required, 3-50 characters
 * - status: Required, 2-50 characters (e.g., OPEN, IN_PROGRESS, RESOLVED)
 * - priority: Required, 2-50 characters (e.g., LOW, MEDIUM, HIGH, CRITICAL)
 * - customerId: Required, must be a valid positive number
 * - assignedTo: Optional, user ID to assign the ticket
 *
 * @author Enterprise Backend Team
 * @version 1.0
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
@EqualsAndHashCode
public class CreateTicketRequest {

    /**
     * Unique ticket number - provided by client or auto-generated by service.
     * Must be unique across all tickets in the system.
     */
    @NotBlank(message = "Ticket number cannot be blank")
    @Size(min = 3, max = 50, message = "Ticket number must be between 3 and 50 characters")
    private String ticketNumber;

    /**
     * Initial status of the ticket (typically OPEN).
     * Valid values: OPEN, IN_PROGRESS, RESOLVED, CLOSED, ON_HOLD
     */
    @NotBlank(message = "Status cannot be blank")
    @Size(min = 2, max = 50, message = "Status must be between 2 and 50 characters")
    private String status;

    /**
     * Priority level of the ticket.
     * Valid values: LOW, MEDIUM, HIGH, CRITICAL
     */
    @NotBlank(message = "Priority cannot be blank")
    @Size(min = 2, max = 50, message = "Priority must be between 2 and 50 characters")
    private String priority;

    /**
     * Customer ID who is creating the ticket.
     * Must reference a valid customer in the system.
     */
    @NotNull(message = "Customer ID cannot be null")
    private Long customerId;

    /**
     * Optional: User ID to assign the ticket to.
     * If not provided, ticket remains unassigned.
     */
    private Integer assignedTo;
}

